### ISSUE TITLE
Nearest Neighbor algorithm

### ISSUE THREAD

**Issue by adibaba** [dice-group/embeddings.cc#29]
Suggested by Stefan (2022-03-15):

- N2 (https://github.com/kakao/n2)
- ScaNN (https://github.com/google-research/google-research/tree/master/scann).

Can properly be integrated in ES by using ES scripts and Java. See:

- https://www.elastic.co/guide/en/elasticsearch/reference/7.16/modules-scripting.html
- Related issue: https://github.com/dice-group/embeddings.cc/issues/24

**Comment by adibaba** [comment]
Update: We can use the ESv8 instance here: https://embeddings.cs.upb.de:9208/ 

Right now, there is less data. If anyone (DICE) needs the password, please ask me in the chat.

**Comment by adibaba** [comment]
I tried a query on the currently running ES8. The mappings ([see](https://embeddings.cs.upb.de:9208/dbp_en_fr_15k/_mapping)) for the index at the online instance are not complete. An "An index value of true" is required ([see](https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#approximate-knn)). So to test it locall, the mappings have to be extended.

```bash
curl -k -X GET "https://elastic:<PASSWORD>@embeddings.cs.upb.de:9208/dbp-en-fr-15k/_knn_search?pretty" -H 'Content-Type: application/json' -d'
{
  "knn": {
    "field": "embeddings",
    "query_vector": [0.3, 0.1, 1.2],
    "k": 10,
    "num_candidates": 100
  },
  "_source": ["name", "date"]
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: to perform knn search on field [embeddings], its mapping must have [index] set to [true]",
        "index_uuid" : "QkPTRKMnTCSkL6MPoB5a7g",
        "index" : "dbp_en_fr_15k"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "dbp_en_fr_15k",
        "node" : "UMzKn404R9uMB5AM65WSzQ",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: to perform knn search on field [embeddings], its mapping must have [index] set to [true]",
          "index_uuid" : "QkPTRKMnTCSkL6MPoB5a7g",
          "index" : "dbp_en_fr_15k",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "to perform knn search on field [embeddings], its mapping must have [index] set to [true]"
          }curl -k -X GET "https://elastic:<PASSWORD>@embeddings.cs.upb.de:9208/dbp-en-fr-15k/_knn_search?pretty" -H 'Content-Type: application/json' -d'
{
  "knn": {
    "field": "embeddings",
    "query_vector": [0.3, 0.1, 1.2],
    "k": 10,
    "num_candidates": 100
  },
  "_source": ["name", "date"]
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: to perform knn search on field [embeddings], its mapping must have [index] set to [true]",
        "index_uuid" : "QkPTRKMnTCSkL6MPoB5a7g",
        "index" : "dbp_en_fr_15k"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "dbp_en_fr_15k",
        "node" : "UMzKn404R9uMB5AM65WSzQ",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: to perform knn search on field [embeddings], its mapping must have [index] set to [true]",
          "index_uuid" : "QkPTRKMnTCSkL6MPoB5a7g",
          "index" : "dbp_en_fr_15k",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "to perform knn search on field [embeddings], its mapping must have [index] set to [true]"
          }
        }
      }
    ]
  },
  "status" : 400
}

        }
      }
    ]
  },
  "status" : 400
}

```

**Comment by adibaba** [comment]
note for myself: lecture https://www.cs.cornell.edu/courses/cs4780/2018fa/syllabus/

**Comment by jiaaayiii** [comment]
test in 1000 data
curl 
curl GET "https://localhost:9200/my-approx-knn-index/_knn_search?pretty" -H 'Content-Type: application/json' -d'

{
  "knn": {
    "field": "my-image-vector",
    "query_vector": [-0.5, 90.0, 120, 14.8, 230.0],
    "k": 3,
    "num_candidates": 10 
  },
  "fields": [
    "my-image-vector",
    "my-tag"
  ]
}
'
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10,
      "relation" : "eq"
    },
    "max_score" : 1.4494245E-4,
    "hits" : [
      {
        "_index" : "my-approx-knn-index",
        "_id" : "753",
        "_score" : 1.4494245E-4,
        "_source" : {
          "my-image-vector" : [
            -12,
            69,
            150,
            5,
            157
          ],
          "my-tag" : "753"
        },
        "fields" : {
          "my-tag" : [
            "753"
          ],
          "my-image-vector" : [
            -12,
            69,
            150,
            5,
            157
          ]
        }
      },
      {
        "_index" : "my-approx-knn-index",
        "_id" : "934",
        "_score" : 1.3383494E-4,
        "_source" : {
          "my-image-vector" : [
            -25,
            39,
            114,
            69,
            194
          ],
          "my-tag" : "934"
        },
        "fields" : {
          "my-tag" : [
            "934"
          ],
          "my-image-vector" : [
            -25,
            39,
            114,
            69,
            194
          ]
        }
      },
      {
        "_index" : "my-approx-knn-index",
        "_id" : "913",
        "_score" : 1.2733192E-4,
        "_source" : {
          "my-image-vector" : [
            10,
            23,
            153,
            3,
            185
          ],
          "my-tag" : "913"
        },
        "fields" : {
          "my-tag" : [
            "913"
          ],
          "my-image-vector" : [
            10,
            23,
            153,
            3,
            185
          ]
        }
      }
    ]
  }
}

**Comment by jiaaayiii** [comment]
step1:curl   -k -X PUT "https://localhost:9200/nomal_query"  -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "my-image-vector": {
        "type": "dense_vector",
        "dims": 5
      },
      "my-tag": {
        "type": "keyword"
      }
    }
  }
}
'
step2:insert 1000 data in nomal_query
step3:curl  -k -X PUT "https://localhost:9200/new_nomal_query"  -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "my-image-vector": {
        "type": "dense_vector",
        "dims": 5,
        "index": true,
        "similarity": "l2_norm"
      },
      "my-tag": {
        "type": "keyword"
      }
    }
  }
}
'


step4：curl -k -X POST "https://localhost:9200/_reindex?pretty" -H 'Content-Type: application/json' -d'
 {
  "source": {
     "index": "nomal_query"
   },
  "dest": {
    "index": "new_nomal_query"
   }
 }
 '

**Comment by adibaba** [comment]
- I reverted some code parts in the es8update branch which will not be used in the future.
- You can still access your old code version here:  
https://github.com/dice-group/embeddings.cc/tree/c07323df0abc1f3dba197ca75b49af0e2139048a
- To check which changes you made, check:  
https://github.com/dice-group/embeddings.cc/compare/fd2e5c5..c07323d
- To check the current changes which are going to be integrated, you can use this link:  
https://github.com/dice-group/embeddings.cc/compare/master..es8update

**Comment by adibaba** [comment]
Single steps:

1. python [create_index()](https://github.com/dice-group/embeddings.cc/blob/fd2e5c53e97b01d5ab27b40a9470e99a56c4b381/webservice_index/__init__.py#L99): modify to have NN in it.
2. python [add()](https://github.com/dice-group/embeddings.cc/blob/fd2e5c53e97b01d5ab27b40a9470e99a56c4b381/webservice_index/__init__.py#L169): maybe modify to add embeddings with NN.
3. Check data. The data will probably be available here at the [ftp server](https://hobbitdata.informatik.uni-leipzig.de/UniKGE/). (Maybe ask JK)
4. Check if [available scripts](https://github.com/dice-group/embeddings.cc/tree/upload-script/api) work with the data to add. (Maybe ask JK)
5. Add (part of) the data locally (i.e. on your machine)
6. If everything works, add data on VM

**Comment by jiaaayiii** [comment]
1. done
2. I think we won't add some KNN in add(), I used CURL to add one data without defining some special KNN part.
3. I will ask Jean later
4,5,6 will follow the sequence.

**Comment by jiaaayiii** [comment]
Now the problem I'm having is that I need to insert the CURL command
curl --user elastic:123456  -k -X GET "https://localhost:9200/index_test/_knn_search?pretty" -H 'Content-Type: application/json' -d'
{
  "knn": {
    "field": "embeddings",
    "query_vector": embedding,
    "k": 10,
    "num_candidates": 10
  }
}
'
inserted into def get_similar_embeddings(index, embeddings).

**Comment by adibaba** [comment]
I created a list of some documentations of the used libraries: https://github.com/dice-group/embeddings.cc/blob/master/docs/development.md

In the python documentation, there is such a method, maybe that can be used:
https://elasticsearch-py.readthedocs.io/en/v8.1.3/api.html?highlight=knn#elasticsearch.Elasticsearch.knn_search

**Comment by jiaaayiii** [comment]
I defined the function following my CURL. But it always :
ValueError
ValueError: Couldn't merge 'body' with other parameters as it wasn't a mapping. Instead of using 'body' use individual API parameters, which does something I missing, I think I have included the mapping part(embeddings), could you help me check the following lines?

def get_similar_embeddings(index, embeddings):
    request = []
    for embedding in embeddings:
        req_head = {'index': index }
        req_body = {
                "knn": {
               "field": 'embeddings',
              "query_vector":embedding,
               "k": 10,
               "num_candidates": 10
        },
         "_source": ["id","entity"]
            }
            
            
        request.extend([req_head, req_body])
        response = get_es().knn_search(body = request)
        
    results = []
    for i, resp in enumerate(response['responses']):
        for hit in resp['hits']['hits']:
         results.append((i, hit['_score'] - 1, hit['_source']['entity'], hit['_source']['embeddings']))
    return results

**Comment by adibaba** [comment]
Checking the code lines would be easier if embedded in the code. Could you push it into git?
Also searching for the error message using google or stackoverflow would make sense, as other developers may already asked for the message.

**Comment by jiaaayiii** [comment]
Finally, figure out the API function, basically, it can run without error, but the result[]  filtered by response should be considered again and changed some more.
`def get_similar_embeddings(index, embeddings):
    i=0
    results = []
    for embedding in embeddings:
     response = get_es().knn_search(index=index,body={"knn":{
                "field":"embeddings",
                "query_vector":embedding,
                "k": 10,
                "num_candidates": 100}
})
     print(response)
    for hit in response['hits']['hits']:
              results.append((i, hit['_score'], hit['_source']['entity'], hit['_source']['embeddings']))
              i=1+1
    return results

`

**Comment by adibaba** [comment]
Current state (to check by me and to integrate afterwards):

- Branch [es8update](https://github.com/dice-group/embeddings.cc/tree/es8update)
  - [fd2e5c5..c07323d](https://github.com/dice-group/embeddings.cc/compare/fd2e5c5..c07323d)
  - [fd2e5c5..2dc177a](https://github.com/dice-group/embeddings.cc/compare/fd2e5c5..2dc177a)
    - embeddings_cc_index_examples.py: no change of boolean values
    - embeddings_cc_index_examples.py: no reading of local file
    - geerate.py: data from local file not required
    - \_\_init\_\_.py main changes to **create index with knn**
